name: Lint

on: [push, pull_request]

jobs:
  lint:
    name: Auto Lint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm ci

      - name: Run ESLint and Prettier
        run: |
          npx eslint --fix src/**/*
          npx prettier --write src/**/*
        working-directory: ./

      - name: Commit changes
        run: |
          git add .
          git commit --amend --no-edit
        working-directory: ./
